name: TeleportationRunes
main: net.blufenix.teleportationrunes.TeleportationRunes
version: 1.0
commands:
   tr:
      description: Show information about Waypoints or reload configuration.
      usage: /<command> [ reload | list ]