TeleportationRunes:
  enabled: true
  debug: false

  # the XP cost for teleportation
  # supported variables:
  #   distance - how far apart the waypoint and teleporter are
  #   anotherWorld - will be set to 0 if teleport occurs withing the same world, or 1 if across worlds
  #
  costFormula: (distance / 25)
  # another examples...
  #
  # make teleportation across worlds cost an extra 100 XP
  #   costFormula: (distance / 25) + anotherWorld * 100
  #

  # whether teleporting costs XP for players in creative mode
  costXpInCreative: false

  # whether teleporters and waypoints can be arbitrarily rotated
  # this will increase CPU usage and may cause lag
  enableRotation: false

  # whether or not to allow teleportation between worlds
  # when using this feature, you may wish to use the variable called 'anotherWorld' in your cost formula
  allowTeleportBetweenWorlds: true

  # whether or not to strike lightning (non-damaging) whenever a player teleports
  enableLightningEffect: false

  # whether or not to use enderman-like teleport effects
  enableEnderTeleportEffect: true

  # delay of teleportation in ticks (20 ticks per second for a normal server)
  # default value is 3 seconds, but you can also make it longer based on distance
  # for example, a minimum of 1 second, plus 1 second for every 100 blocks:
  #teleportDelayFormula: (1 + (distance / 100)) * 20
  teleportDelayFormula: 60

  # whether or not Book of Ender should be consumed on successful use
  # will not consume if waypoint was already activated, or could not be activated
  consumeBook: false

  # how many scrolls to craft when creating a scroll of warp
  numScrollsCrafted: 4

  # allow already-attuned scrolls to be re-attuned
  allowReattune: true

  # database backend will default to SQLITE, except for FreeBSD which uses HSQLDB
  # or, you can specify a value here to force one or the other.
  #databaseBackend: SQLITE
  #databaseBackend: HSQLDB

  # shapeless recipe for Book of Ender
  bookOfEnder:
    recipe:
      - BOOK
      - ENDER_PEARL

  # shapeless recipe for Scroll of Warp
  scrollOfWarp:
    recipe:
      - PAPER
      - ENDER_PEARL

  # animation settings when particles swirl around a teleporting player
  # only radius and rotations are floating point values, all other numbers must be integers
  # duration of animation is controlled by teleportDelayFormula, since the animation is intended to match
  particleAnimation:
    enabled: true
    particleType: SPELL_WITCH
    radius: 4.0
    segments: 3
    particles: 10
    rotations: 1.5
    cycles: 1
    # the animation duty cycle controls how many ticks must elapse before more particles are drawn
    # 1 is the lowest value, and will give the smoothest animation
    # increase this value if you experience lag
    dutyCycle: 1
    # to compensate for a dutyCycle greater than 1, you can use this setting to animate all the frames that would
    # have been skipped. Rather than 1 frame per tick, you will animate a number of frames equal to the duty cycle,
    # but all at once. This value is effectively ignored when dutyCycle is 1.
    # disable this if bumping up the duty cycle doesn't fix lag
    animateAllFrames: true

  blueprint:
    materials:
      # you can configure these in any way you want, but some characters (like a question mark, '?') will cause issues
      # For example, do NOT do this:
      # ?: ANY_BLOCK
      #
      # You don't have to use single characters, but doing so will make your teleporter/waypoint layers much easier to read
      # For example, this is valid, but really ugly:
      # MyFourthBlock: SIGNATURE_BLOCK_4

      $: ANY_BLOCK

      N: SIGNATURE_BLOCK_1
      S: SIGNATURE_BLOCK_2
      E: SIGNATURE_BLOCK_3
      W: SIGNATURE_BLOCK_4

      # These are arbitrary. Keys can be any letter or string (that isn't used above),
      # and each material value must be a valid material name.
      R: REDSTONE_BLOCK
      L: LAPIS_BLOCK
      D: DIAMOND_BLOCK
      I: IRON_BLOCK

    teleporter:
      layers:
        -
          - [R,N,R]
          - [W,R,E]
          - [R,S,R]

      clickableBlock:
          ==: Vector
          x: 1.0
          y: 0.0
          z: 1.0

    waypoint:
      layers:
        -
          - [L,N,L]
          - [W,L,E]
          - [L,S,L]

      clickableBlock:
          ==: Vector
          x: 1.0
          y: 0.0
          z: 1.0
