TeleportationRunes:
  enabled: true
  costFormula: (distance / 10)
  tempTeleporterMaterial: REDSTONE_WIRE

  blueprint:
    materials:
      $: ANY_BLOCK

      N: SIGNATURE_BLOCK_1
      S: SIGNATURE_BLOCK_2
      E: SIGNATURE_BLOCK_3
      W: SIGNATURE_BLOCK_4

      R: REDSTONE_BLOCK
      L: LAPIS_BLOCK
      D: DIAMOND_BLOCK
      I: IRON_BLOCK

    teleporter:
      layers:
        -
          - [$,$,$,R,$,$,$]
          - [$,$,R,N,R,$,$]
          - [$,R,R,R,R,R,$]
          - [R,W,R,D,R,E,R]
          - [$,R,R,R,R,R,$]
          - [$,$,R,S,R,$,$]
          - [$,$,$,R,$,$,$]

      clickableBlock:
          ==: Vector
          x: 3.0
          y: 0.0
          z: 3.0

    waypoint:
      layers:
        -
          - [$,N,$]
          - [$,L,$]
          - [$,L,$]
          - [$,L,$]
          - [$,D,$]
          - [W,S,E]

      clickableBlock:
          ==: Vector
          x: 4.0
          y: 0.0
          z: 1.0


  #
  # suggested formulas:
  #
  # Default. This costs 1 experience point for every 10 blocks traveled:
  # costFormula: (distance / 10)
  #
  # Make teleporting to much higher/lower places, like mines
  # or dungeons, more expensive:
  # costFormula: (distance / 10) * (1 + deltaY/100)
  #
  # Charge double EXP for teleporting with a horse:
  # costFormula: (distance / 10) * numEntities
  #
  # A combination of the previous two formulas:
  # costFormula: (distance / 10) * (1 + deltaY/100) * numEntities
  #
  # valid variables are: distance deltaX deltaY deltaZ numEntities
