TeleportationRunes:
  enabled: true
  costFormula: (distance / 25)
  enableRotation: false
  debug: false

  # whether or not Book of Ender should be consumed on successful use
  # will not consume if waypoint was already activated, or could not be activated
  consumeBook: false

  # how many scrolls to craft when creating a scroll of warp
  numScrollsCrafted: 4

  # database backend will default to SQLITE, except for FreeBSD which uses HSQLDB
  # or, you can specify a value here to force one or the other.
  #databaseBackend: SQLITE
  #databaseBackend: HSQLDB

  blueprint:
    materials:
      # you can configure these in any way you want, but some characters (like a question mark, '?') will cause issues
      # For example, do NOT do this:
      # ?: ANY_BLOCK
      #
      # You don't have to use single characters, but doing so will make your teleporter/waypoint layers much easier to read
      # For example, this is valid, but really ugly:
      # MyFourthBlock: SIGNATURE_BLOCK_4

      $: ANY_BLOCK

      N: SIGNATURE_BLOCK_1
      S: SIGNATURE_BLOCK_2
      E: SIGNATURE_BLOCK_3
      W: SIGNATURE_BLOCK_4

      R: REDSTONE_BLOCK
      L: LAPIS_BLOCK
      D: DIAMOND_BLOCK
      I: IRON_BLOCK

    teleporter:
      layers:
        -
          - [R,N,R]
          - [W,R,E]
          - [R,S,R]

      clickableBlock:
          ==: Vector
          x: 1.0
          y: 0.0
          z: 1.0

    waypoint:
      layers:
        -
          - [L,N,L]
          - [W,L,E]
          - [L,S,L]

      clickableBlock:
          ==: Vector
          x: 1.0
          y: 0.0
          z: 1.0
