TeleportationRunes:
  enabled: true
  costFormula: (distance / 10)
  waypointMaterial: LAPIS_BLOCK
  teleporterMaterial: REDSTONE_BLOCK

  #
  # suggested formulas:
  #
  # Default. This costs 1 experience point for every 10 blocks traveled:
  # costFormula: (distance / 10)
  #
  # Make teleporting to much higher/lower places, like mines
  # or dungeons, more expensive:
  # costFormula: (distance / 10) * (1 + deltaY/100)
  #
  # Charge double EXP for teleporting with a horse:
  # costFormula: (distance / 10) * numEntities
  #
  # A combination of the previous two formulas:
  # costFormula: (distance / 10) * (1 + deltaY/100) * numEntities
  #
  # valid variables are: distance deltaX deltaY deltaZ numEntities
