name: TeleportationRunes
main: net.blufenix.teleportationrunes.TeleportationRunes
version: 2.0.0
api-version: 1.13
commands:
   tr:
      description: Show information about Waypoints or reload configuration.
      usage: |
             TeleportationRunes command usage:
                 /<command> reload
