name: TeleportationRunes
main: net.blufenix.teleportationrunes.TeleportationRunes
version: 2.1.0-beta
api-version: 1.16
commands:
   tr:
      description: Show information about Waypoints or reload configuration.
      usage: |
             TeleportationRunes command usage:
                 /<command> reload
                 /<command> convertdb
                 /<command> mirage <teleporter|waypoint>
