name: TeleportationRunes
main: net.blufenix.teleportationrunes.TeleportationRunes
version: 1.9.9
commands:
   tr:
      description: Show information about Waypoints or reload configuration.
      usage: |
             TeleportationRunes command usage:
                 /<command> reload
